version = 0.1

[default.deploy.parameters]
stack_name = "ai-incident-summarizer"
resolve_s3 = true
s3_prefix = "ai-incident-summarizer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "GithubWebhookSecretArn=\"arn:aws:secretsmanager:us-east-1:727323477998:secret:gh-webhook-secret-MOOKhC\" DatadogWebhookSecretArn=\"arn:aws:secretsmanager:us-east-1:727323477998:secret:dd-webhook-secret-IMmuhX\" AnthropicApiKeySecretArn=\"arn:aws:secretsmanager:us-east-1:727323477998:secret:anthropic-api-key-EcJjQi\" SlackBotTokenSecretArn=\"arn:aws:secretsmanager:us-east-1:727323477998:secret:incident-summarizer-slackbot-BabPAw\" SlackChannelId=\"C0B4L4L5H4J\" JiraApiTokenSecretArn=\"arn:aws:secretsmanager:us-east-1:727323477998:secret:stale-bot/jira-api-token-LUZhBM\" JiraBaseUrl=\"https://hirereidcollins.atlassian.net\" JiraProjectKey=\"INC\" JiraUserEmail=\"hire.reid.collins@gmail.com\" DatadogApiKeySecretArn=\"arn:aws:secretsmanager:us-east-1:727323477998:secret:DD_API_KEY-0mK2ke\" DatadogEnv=\"dev\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
